# Generated by Django 2.2.7 on 2020-04-15 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('fecha_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código único para cada producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo', models.FloatField(default=0.0)),
                ('fecha_emicion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código único para cada venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('fecha_venta', models.DateField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('medida', models.FloatField(default=0.0)),
                ('preparacion', models.TextField(blank=True, null=True)),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Ingrediente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Producto')),
            ],
        ),
    ]
