# Generated by Django 2.2.7 on 2020-04-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20200417_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='receta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Receta'),
        ),
        migrations.AddField(
            model_name='receta',
            name='ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Ingrediente'),
        ),
    ]
