# Generated by Django 2.2.7 on 2020-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20200417_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='fecha_compra',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_emicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(),
        ),
    ]
