# Generated by Django 2.2.7 on 2020-04-19 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_auto_20200417_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_emicion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
