# Generated by Django 2.2.7 on 2020-04-21 17:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código unico para cada compra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField(default=0.0)),
                ('fecha_compra', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
