# Generated by Django 2.2.7 on 2020-05-01 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadecompra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
