# Generated by Django 3.0.5 on 2020-06-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20200430_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineadecompra',
            name='total_peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineadecompra',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
