# Generated by Django 2.2.7 on 2020-04-22 01:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código único para cada producto', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo', models.FloatField(default=0.0)),
                ('fecha_emicion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('receta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recetarios.Receta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código único para cada venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto')),
            ],
        ),
    ]
