# Generated by Django 2.2.7 on 2020-04-21 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código único para cada venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Producto')),
            ],
        ),
    ]
