# Generated by Django 2.2.7 on 2020-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('medida', models.FloatField()),
                ('descripcion', models.TextField(blank=True, help_text='Esta descripcion es opcional', null=True)),
            ],
        ),
    ]
