# Generated by Django 2.2.7 on 2020-04-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, help_text='Esta descripcion es opcional', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elaboracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.FloatField(default=0.0)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetarios.Receta')),
            ],
        ),
    ]
