# Generated by Django 2.2.7 on 2020-05-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elaboracion',
            options={'verbose_name': 'Elaboracion'},
        ),
    ]
